name: Generate Changelog and Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies
              run: npm install

            - name: Generate Changelog
              run: npm run generate-changelog

            - name: Create Release Commit and Tag
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add CHANGELOG.md
                  git commit -m "Update CHANGELOG.md"
                  git tag v$(node -p "require('./package.json').version")
                  git push origin HEAD:main --tags

            - name: Create GitHub Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v$(node -p "require('./package.json').version")
                  release_name: Release v$(node -p "require('./package.json').version")
                  body_path: CHANGELOG.md
                  draft: false
                  prerelease: false
